/**
 * Mirrors ap_ds_storybook's .storybook/main.js: stories live next to their
 * components, staticDirs serves the generated token CSS so preview.jsx can
 * import it directly.
 *
 * INTERNAL-ONLY STORIES: package.json's "build-storybook" script is
 * `npm run build && storybook build` -- npm sets `npm_lifecycle_event` to
 * the currently-running script's name for that whole shell invocation
 * (including "storybook build", spawned as its child process via `&&`),
 * so it reliably reads "build-storybook" there and "storybook" during
 * `npm run storybook` (dev). internal/[star][star]/[star].stories.jsx (see
 * internal/StorybookDS/) lives OUTSIDE components/, so it's never swept
 * up by the main glob below -- it's only added to `stories` at all when
 * NOT running the public build, which is what `npm run deploy-storybook`
 * publishes. This makes it structurally impossible for an internal-only
 * story to end up in storybook-static/ or gh-pages, rather than relying
 * on remembering not to deploy while one exists.
 */
const isPublicBuild = process.env.npm_lifecycle_event === "build-storybook";

const stories = ["../components/**/*.stories.@(js|jsx)"];
if (!isPublicBuild) {
	stories.push("../internal/**/*.stories.@(js|jsx)");
}

const config = {
	stories,
	// addon-a11y is deliberately not listed: its Accessibility tab was the
	// only bottom-panel tab left with any content, and the whole panel is
	// hidden now (see manager.js). @storybook/addon-a11y is still installed
	// in package.json -- add it back here (and drop the showPanel override
	// in manager.js) to bring the panel back.
	addons: ["@storybook/addon-docs"],
	// Storybook 10's built-in Controls/Actions/Interactions panels are
	// switched off: every story here is a plain render() with no args,
	// argTypes, fn() actions, or play functions, so those tabs were always
	// empty ("This story has no controls"). If the Button Playground page
	// (argTypes + Controls) gets built later, flip `controls` back to true
	// and re-enable the panel in manager.js.
	features: {
		controls: false,
		actions: false,
		interactions: false,
	},
	framework: {
		name: "@storybook/react-vite",
		options: {},
	},
	// build/ is regenerated by `npm run build` (build-tokens.js +
	// generate-color-manifest.js) before every `storybook`/`build-storybook`
	// run -- see package.json scripts.
	staticDirs: ["../build"],
};

export default config;
